# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "1800mini"
product_name = " SI_RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P6", "P8", "P17", "P20", "P22"]
output_pins = ["P24","P1_00","P11","P1_04","P1_06","P12", "P23", "P21", "P19", "P7", "P9", "P10", "P2", "P29", "P31"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 4
cols = 15
layers = 4
keymap = [
    [
    [k!(Grave),k!(Q), k!(W), k!(E), k!(R), k!(T), k!(Y), k!(U), k!(I), k!(O), k!(P),k!(Backspace), k!(Kc7), k!(Kc8), k!(Kc9)],
    [k!(Escape), k!(A), k!(S), k!(D), k!(F), k!(G), k!(H), k!(J), k!(K), k!(L),k!(Enter), a!(No), k!(Kc4), k!(Kc5), k!(Kc6)],
    [k!(LShift), k!(Z), k!(X), k!(C), k!(V), k!(B), k!(N), k!(M), k!(Slash),k!(RShift),a!(No), UP,k!(Kc1), k!(Kc2), k!(Kc3)],
    [k!(LCtrl), k!(LGui), k!(LAlt),k!(Space), a!(No), a!(No),k!(Space), a!(No), mo!(1),LEFT,DOWN,RIGHT,Dot, k!(Kc0),]
    ],
    [
    ["_","_","_","_","_","_","_","_","_","_","_","_","_","_","_"],
    ["_","_","_","_","_","_","_","_","_","_","_","_","_","_","_"],
    ["_","_","_","_","_","_","_","_","_","_","_","_","_","_"],
    ["_","_","_","_","_","_","_","_","_","_","_","_"]
    ]
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
